platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'WZPresentationController_Example' do
  pod 'WZPresentationController', :path => '../'

  target 'WZPresentationController_Tests' do
    inherit! :search_paths

  end
end
